CREATE DATABASE IF NOT EXISTS ContactosDB;

USE ContactosDB;

CREATE TABLE IF NOT EXISTS Contactos (
    Id INT AUTO_INCREMENT PRIMARY KEY,
    Nombre VARCHAR(100) NOT NULL,
    Telefono VARCHAR(20)
);
